name: movemint_user
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  google_places_flutter: ^2.0.8
  another_stepper: ^1.2.2
  firebase_auth: ^4.2.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanExtraBold.ttf
          weight: 800
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
