name: movemint_user
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  dio: ^5.4.2+1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^6.0.1
  fluttertoast: ^8.2.4
  flutter_typeahead: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  flutter_svg_provider: ^1.0.7
  intl:
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.1
  permission_handler:
  lottie: ^3.1.0
  provider: ^6.1.1
  google_places_flutter: ^2.0.8
  another_stepper: ^1.2.2
  firebase_auth: ^4.2.2
  url_launcher: ^6.2.3
  uuid: ^4.3.3


# Create launcher icon for both android and ios
# Use these commands to create flutter launcher icons:
# 1. flutter pub get
# 2. flutter pub run flutter_launcher_icons

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_group_1171281249.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_lints:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/lottie/
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanExtraBold.ttf
          weight: 800
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
